
### create user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "pikita",
    "email": "kolchin.nv@gmail.com",
    "password": "123"
}

### update user
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "email": "dukita@mail.ru",
    "username": "nikita"
}

### update contribution
POST http://localhost:3000/api/users/signin
Content-Type: application/json

{
    "email": "dukita@mail.ru",
    "password":"123"
}

### delete user
DELETE http://localhost:3000/api/users/1

### get users
GET  http://localhost:3000/api/users/



